[package]
name = "kid-recipe"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license-file.workspace = true
readme.workspace = true
keywords = ["recipe", "command-runner", "task-runner"]

[lints]
workspace = true

[lib]
name = "recipe"

[[bin]]
name = "kid-recipes"
path = "src/main.rs"

[dependencies]
clap.workspace = true
indexmap = { workspace = true, features = ["serde"] }
serde.workspace = true
toml.workspace = true

[dev-dependencies]
assert_fs.workspace = true
indoc.workspace = true
