//! MCP (Model Context Protocol) server exposing text-editor tools
//! scoped to a single workspace directory.
//! All paths, relative or absolute, are resolved against the workspace root
//! and rejected if they would escape it.
mod create;
mod insert;
mod just_run;
mod str_replace;
mod tree;
mod view;
mod workspace_path;

pub(crate) use just_run::RecipeName;

use anyhow::Result;
use rmcp::handler::server::router::tool::ToolRouter;
use rmcp::handler::server::tool::ToolCallContext;
use rmcp::model::{
    CallToolRequestParams, CallToolResponse, ErrorData as McpError, Implementation,
    ListToolsResult, PaginatedRequestParams, ServerCapabilities, ServerInfo,
};
use rmcp::service::RequestContext;
use rmcp::{RoleServer, ServerHandler};

use std::borrow::Cow;
use std::collections::HashSet;
use std::path::PathBuf;

/// MCP server exposing a text-editor tool, sandboxed to one workspace root.
#[derive(Clone)]
pub struct McpService {
    workspace_root: PathBuf,
    /// Names treated as nonexistent by every tool, e.g. ".git" or "target" —
    /// not just hidden from `tree`, but unreadable, unwritable, and invisible
    /// everywhere a path is resolved.
    ignore: Vec<String>,
    /// Recipes discovered once at construction time. Empty if the
    /// workspace has no `justfile`.
    just_recipes: HashSet<RecipeName>,
    tool_router: ToolRouter<Self>,
}

impl ServerHandler for McpService {
    fn get_info(&self) -> ServerInfo {
        ServerInfo::new(ServerCapabilities::builder().enable_tools().build())
            .with_server_info(Implementation::new(
                "kid-text-editor",
                env!("CARGO_PKG_VERSION"),
            ))
            .with_instructions(
                "File editor scoped to a single workspace. \
                All paths (relative or absolute) are resolved \
                against the workspace root.",
            )
    }

    /// Not generated by `#[tool_handler]` here, because `just_run`'s
    /// description is otherwise fixed at compile time — it can say "runs
    /// a recipe" but not *which* recipes this workspace's `justfile`
    /// actually defines, since that's only known once `just_recipes` is
    /// discovered at startup (see ADR 0003, "a boundary the agent can't
    /// see isn't fully useful"). This appends that list to the
    /// already-built tool description on the way out; it does not change
    /// which recipes are callable — `just_run`'s handler still checks
    /// every call against `self.just_recipes` on its own.
    async fn list_tools(
        &self,
        _request: Option<PaginatedRequestParams>,
        _context: RequestContext<RoleServer>,
    ) -> Result<ListToolsResult, McpError> {
        let mut tools = self.tool_router.list_all();
        if let Some(just_run) = tools.iter_mut().find(|tool| tool.name == "just_run") {
            let base = just_run.description.as_deref().unwrap_or_default();
            let mut recipe_names: Vec<String> = self
                .just_recipes
                .iter()
                .map(RecipeName::to_string)
                .collect();
            recipe_names.sort_unstable();
            let recipes = recipe_names.join(", ");
            just_run.description =
                Some(Cow::Owned(format!("{base} Available recipes: {recipes}.")));
        }
        Ok(ListToolsResult::with_all_items(tools))
    }

    async fn call_tool(
        &self,
        request: CallToolRequestParams,
        context: RequestContext<RoleServer>,
    ) -> Result<CallToolResponse, McpError> {
        self.tool_router
            .call(ToolCallContext::new(self, request, context))
            .await
    }
}

impl McpService {
    /// `just_recipes` is discovered once by the caller (see
    /// `McpServer::serve`), not per session — re-running `just --summary`
    /// on every new connection would be wasted work.
    pub fn new(
        workspace_root: PathBuf,
        ignore: Vec<String>,
        just_recipes: HashSet<RecipeName>,
    ) -> Self {
        let mut tool_router = Self::create_tool_router()
            + Self::insert_tool_router()
            + Self::str_replace_tool_router()
            + Self::tree_tool_router()
            + Self::view_tool_router();
        if !just_recipes.is_empty() {
            tool_router += Self::just_run_tool_router();
        }

        Self {
            workspace_root,
            ignore,
            just_recipes,
            tool_router,
        }
    }
}
