//! MCP (Model Context Protocol) server exposing text-editor tools
//! scoped to a single workspace directory.
//! All paths, relative or absolute, are resolved against the workspace root
//! and rejected if they would escape it.
mod create;
mod insert;
mod recipe_run;
mod search;
mod str_replace;
mod tree;
mod view;
mod workspace_path;

pub(crate) use recipe_run::discover as discover_recipes;
pub use workspace_path::IgnorePattern;

use recipe::RecipeFile;

use anyhow::Result;
use rmcp::handler::server::router::tool::ToolRouter;
use rmcp::handler::server::tool::ToolCallContext;
use rmcp::model::{
    CallToolRequestParams, CallToolResponse, ContentBlock, ErrorData as McpError, Implementation,
    ListToolsResult, PaginatedRequestParams, ServerCapabilities, ServerInfo,
};
use rmcp::service::RequestContext;
use rmcp::{RoleServer, ServerHandler};
use serde_json::Value;

use std::path::PathBuf;

/// MCP server exposing a text-editor tool, sandboxed to one workspace root.
#[derive(Clone)]
pub struct McpService {
    workspace_root: PathBuf,
    /// Glob patterns treated as nonexistent by every tool, e.g. ".git",
    /// "target", or "*.log" — not just hidden from `tree`, but unreadable,
    /// unwritable, and invisible everywhere a path is resolved. See
    /// [`IgnorePattern`] for the matching rules.
    ///
    /// When [`recipe_toml_protected_path`](Self::recipe_toml_protected_path)
    /// is `Some`, this also includes an [`IgnorePattern::exact_path`] for
    /// that one path — added here in [`McpService::new`], not via
    /// `--ignore`, so protection stays tied to whether `recipe_run` is
    /// actually offered rather than to ordinary, user-editable ignore
    /// configuration.
    ignore: Vec<IgnorePattern>,
    /// The workspace-relative path of the file passed via
    /// `--recipes-file`, write-refused (`into_write_buffer`) and folded
    /// into `ignore` above, if and only if that file actually lies
    /// inside the workspace. `None` covers both "no `--recipes-file`
    /// passed" and "passed, but the file is outside the workspace" — the
    /// latter needs no protection since every tool here already can't
    /// reach outside the workspace root regardless. See ADR 0004's
    /// "More Information" amendment.
    recipe_toml_protected_path: Option<PathBuf>,
    /// Recipes read once at construction time from the path passed via
    /// `--recipes-file`. Empty if that flag wasn't passed or the file
    /// doesn't exist — see ADR 0004.
    recipes: RecipeFile,
    tool_router: ToolRouter<Self>,
}

impl ServerHandler for McpService {
    fn get_info(&self) -> ServerInfo {
        ServerInfo::new(ServerCapabilities::builder().enable_tools().build())
            .with_server_info(Implementation::new(
                "kid-text-editor",
                env!("CARGO_PKG_VERSION"),
            ))
            .with_instructions(
                "File editor scoped to a single workspace. \
                All paths (relative or absolute) are resolved \
                against the workspace root.",
            )
    }

    /// Not generated by `#[tool_handler]` here, because per-recipe tools
    /// (see ADR 0005) are only known once `recipes.toml` is read at
    /// startup, not at compile time. `tool_router` covers everything
    /// else; the per-recipe tools are appended on the way out.
    async fn list_tools(
        &self,
        _request: Option<PaginatedRequestParams>,
        _context: RequestContext<RoleServer>,
    ) -> Result<ListToolsResult, McpError> {
        let mut tools = self.tool_router.list_all();
        tools.extend(recipe_run::tools(&self.recipes));
        Ok(ListToolsResult::with_all_items(tools))
    }

    async fn call_tool(
        &self,
        request: CallToolRequestParams,
        context: RequestContext<RoleServer>,
    ) -> Result<CallToolResponse, McpError> {
        let tool_name = request.name.to_string();
        let path = request
            .arguments
            .as_ref()
            .and_then(|args| args.get("path"))
            .and_then(Value::as_str)
            .unwrap_or("-")
            .to_owned();
        tracing::info!(tool = %tool_name, path = %path, "tool called");
        tracing::debug!(tool = %tool_name, arguments = ?request.arguments, "tool arguments");

        let result = if let Some(result) = recipe_run::call(
            &self.recipes,
            &request.name,
            request.arguments.as_ref(),
            &self.workspace_root,
        ) {
            result.map(Into::into)
        } else {
            self.tool_router
                .call(ToolCallContext::new(self, request, context))
                .await
        };

        match &result {
            Ok(response) => {
                let output = output_text(response);
                tracing::info!(tool = %tool_name, output_chars = output.chars().count(), "tool succeeded");
                tracing::debug!(tool = %tool_name, output = %output, "tool output");
            }
            Err(error) => tracing::info!(tool = %tool_name, %error, "tool failed"),
        }

        result
    }
}

/// Renders a tool's result for logging. `CallToolResponse::Complete` is
/// the only variant every tool here produces (no streaming/partial
/// responses in this codebase) — its text blocks are joined for a real
/// char count. Any other variant falls back to `{:?}` rather than
/// failing the log statement over it.
fn output_text(response: &CallToolResponse) -> String {
    let CallToolResponse::Complete(result) = response else {
        return format!("{response:?}");
    };
    result
        .content
        .iter()
        .filter_map(|block| match block {
            ContentBlock::Text(text) => Some(text.text.as_str()),
            _ => None,
        })
        .collect::<Vec<_>>()
        .join("\n")
}

impl McpService {
    /// `recipes` is read once by the caller (see `McpServer::serve`),
    /// not per session. Pass an empty [`RecipeFile`] to leave
    /// `recipe_run`'s tools absent — the default, absent
    /// `--recipes-file`. `recipe_toml_protected_path` must already be
    /// confirmed to lie inside `workspace_root` (relative to it) — see
    /// `McpServer::serve`, which does that check before calling this.
    pub fn new(
        workspace_root: PathBuf,
        mut ignore: Vec<IgnorePattern>,
        recipes: RecipeFile,
        recipe_toml_protected_path: Option<PathBuf>,
    ) -> Self {
        let tool_router = Self::create_tool_router()
            + Self::insert_tool_router()
            + Self::search_tool_router()
            + Self::str_replace_tool_router()
            + Self::tree_tool_router()
            + Self::view_tool_router();

        if let Some(protected) = &recipe_toml_protected_path {
            ignore.push(IgnorePattern::exact_path(protected.clone()));
        }

        Self {
            workspace_root,
            ignore,
            recipe_toml_protected_path,
            recipes,
            tool_router,
        }
    }
}
